export const TOOL_VERBS: Record<string, string> = {
  browser: 'browsing',
  clarify: 'asking',
  create_file: 'creating',
  delegate_task: 'delegating',
  delete_file: 'deleting',
  execute_code: 'executing',
  image_generate: 'generating',
  list_files: 'listing',
  memory: 'remembering',
  patch: 'patching',
  read_file: 'reading',
  run_command: 'running',
  search_code: 'searching',
  search_files: 'searching',
  terminal: 'terminal',
  web_extract: 'extracting',
  web_search: 'searching',
  write_file: 'writing'
}

export const VERBS = [
  'folding',
  'refolding',
  'grafting CDRs',
  'scanning epitopes',
  'counting contacts',
  'humanizing',
  'docking',
  'ranking candidates',
  'checking hotspots',
  'aligning frameworks',
  'sampling sequences',
  'reading paratopes',
  'pipetting in silico',
  'annealing',
  'titrating',
  'threading',
  'mutating',
  'minimizing',
  'packing sidechains',
  'screening',
  'modeling',
  'measuring loops',
  'clustering',
  'scoring',
  'relaxing',
  'superposing',
  'trimming loops',
  'weighing binders',
  'synthesizing',
  'reasoning'
]
