export const TOOL_VERBS: Record<string, string> = {
  browser: 'browsing',
  clarify: 'asking',
  create_file: 'creating',
  delegate_task: 'delegating',
  delete_file: 'deleting',
  execute_code: 'executing',
  image_generate: 'generating',
  list_files: 'listing',
  memory: 'remembering',
  patch: 'patching',
  read_file: 'reading',
  run_command: 'running',
  search_code: 'searching',
  search_files: 'searching',
  terminal: 'terminal',
  web_extract: 'extracting',
  web_search: 'searching',
  write_file: 'writing'
}

export const VERBS = [
  'folding',
  'refolding',
  'grafting CDRs',
  'scanning epitopes',
  'counting contacts',
  'humanizing',
  'docking',
  'ranking candidates',
  'checking hotspots',
  'aligning frameworks',
  'sampling sequences',
  'reading paratopes',
  'pipetting in silico',
  'annealing',
  'titrating',
  'threading',
  'mutating',
  'minimizing',
  'packing sidechains',
  'screening',
  'modeling',
  'measuring loops',
  'clustering',
  'scoring',
  'relaxing',
  'superposing',
  'trimming loops',
  'weighing binders',
  'synthesizing',
  'reasoning',
  'diffusing backbones',
  'hallucinating folds',
  'inpainting loops',
  'denoising atoms',
  'nudging rotamers',
  'herding rotamers',
  'sampling rotamers',
  'packing interfaces',
  'sculpting loops',
  'stapling helices',
  'tracing backbones',
  'maturing affinity',
  'reading salt bridges',
  'burying hydrophobes',
  'counting cysteines',
  'pairing cysteines',
  'bridging disulfides',
  'zipping leucines',
  'stacking aromatics',
  'tickling tryptophans',
  'blaming prolines',
  'dodging prolines',
  'flipping asparagines',
  'flipping histidines',
  'tautomerizing',
  'protonating',
  'glycosylating',
  'deimmunizing',
  'swapping residues',
  'scanning alanines',
  'scanning glycines',
  'checking phi psi',
  'gauging strain',
  'easing strain',
  'probing cavities',
  'carving pockets',
  'filling voids',
  'drilling tunnels',
  'placing waters',
  'counting waters',
  'squeezing waters',
  'shaving clashes',
  'hunting clashes',
  'dodging clashes',
  'resolving clashes',
  'wrestling loops',
  'lassoing loops',
  'calming loops',
  'polishing termini',
  'sniffing hotspots',
  'mapping epitopes',
  'mapping paratopes',
  'courting stability',
  'taming disorder',
  'solvating shells',
  'equilibrating',
  'thermostatting',
  'barostatting',
  'running dynamics',
  'wiggling atoms',
  'jiggling atoms',
  'shaking waters',
  'integrating steps',
  'heating replicas',
  'cooling replicas',
  'swapping replicas',
  'sampling basins',
  'crossing barriers',
  'climbing funnels',
  'surfing landscapes',
  'mapping landscapes',
  'tunneling',
  'chasing entropy',
  'hedging entropy',
  'untangling knots',
  'coaxing convergence',
  'juggling torsions',
  'twisting torsions',
  'spinning dihedrals',
  'herding electrons',
  'redocking',
  'rescoring poses',
  'pruning branches',
  'binning clusters',
  'chasing gradients',
  'clipping gradients',
  'warming schedulers',
  'tuning temperature',
  'sampling logits',
  'decoding greedily',
  'decoding sequences',
  'beaming candidates',
  'embedding motifs',
  'tokenizing',
  'attending heads',
  'pooling features',
  'distilling priors',
  'calibrating scores',
  'bootstrapping',
  'validating splits',
  'splitting folds',
  'auditing leakage',
  'benchmarking',
  'profiling kernels',
  'fusing kernels',
  'compiling kernels',
  'batching requests',
  'padding batches',
  'queuing GPUs',
  'melting GPUs',
  'warming up GPUs',
  'appeasing CUDA',
  'blaming CUDA',
  'counting FLOPs',
  'burning FLOPs',
  'hoarding VRAM',
  'defragmenting VRAM',
  'thrashing caches',
  'warming caches',
  'paging in weights',
  'quantizing weights',
  'sharding weights',
  'checkpointing',
  'unpickling',
  'parsing FASTA',
  'parsing mmCIF',
  'blasting sequences',
  'scanning profiles',
  'profiling HMMs',
  'building MSAs',
  'aligning MSAs',
  'trimming MSAs',
  'deduplicating hits',
  'clustering hits',
  'counting homologs',
  'chasing homologs',
  'crawling UniProt',
  'querying UniProt',
  'mining PDB entries',
  'wrangling PDB files',
  'dusting off PDB',
  'rooting trees',
  'pruning trees',
  'dating divergence',
  'calling variants',
  'annotating domains',
  'sniffing signals',
  'cleaving peptides',
  'digesting trypsin',
  'seeding sequences',
  'quenching flasks',
  'incubating plates',
  'vortexing samples',
  'melting curves',
  'running gels',
  'loading gels',
  'staining gels',
  'blotting membranes',
  'spinning columns',
  'eluting fractions',
  'pooling fractions',
  'dialyzing buffers',
  'buffering exchange',
  'chilling buffers',
  'degassing buffers',
  'calibrating pipettes',
  'changing tips',
  'labeling tubes',
  'thawing aliquots',
  'freezing aliquots',
  'reviving cells',
  'passaging cells',
  'transfecting cells',
  'inducing expression',
  'harvesting pellets',
  'lysing cells',
  'sonicating lysate',
  'clarifying lysate',
  'purifying tags',
  'cleaving tags',
  'polishing SEC',
  'growing crystals',
  'fishing loops',
  'soaking crystals',
  'shooting crystals',
  'phasing reflections',
  'refining density',
  'building density',
  'picking particles',
  'classing particles',
  'averaging classes',
  'sharpening maps',
  'blurring maps',
  'fitting into maps',
  'validating models',
  'checking clashscore',
  'depositing to PDB',
  'queueing on SLURM',
  'pestering SLURM',
  'resubmitting',
  'shaving yaks',
  'bikeshedding',
  'rubberducking',
  'squinting at plots',
  'eyeballing curves',
  'fitting curves',
  'smoothing curves',
  'integrating peaks',
  'assigning peaks',
  'deconvolving peaks',
  'baselining spectra',
  'shimming magnets',
  'counting scans',
  'skimming abstracts',
  'citing prior art',
  'rebutting reviewers',
  'brewing coffee'
]
