"""Names LiteLLM routes to, snapshotted so reporting need not import LiteLLM.

Importing LiteLLM costs about two seconds and pulls in the OpenAI SDK, httpx and
tiktoken. That is fine for a command that is about to call a model and wrong for
one that only reports what is configured.
This snapshot lets the read-only paths answer "does LiteLLM route to this name?"
for free; a name absent from it still falls through to LiteLLM itself wherever
the answer has to be authoritative.

Generated from litellm 1.100.0. A guard test compares it against the installed
LiteLLM, so a version bump that adds or drops a provider fails there rather than
silently hiding a vendor from `provider list`. Regenerate with:

    uv run python -c "import litellm; print(chr(10).join(sorted({str(getattr(p,'value',p)) for p in litellm.provider_list})))"
"""

from __future__ import annotations

# Sorted, so a regeneration diff shows only what LiteLLM actually changed.
LITELLM_PROVIDER_NAMES: frozenset[str] = frozenset(
    (
        "a2a",
        "a2a_agent",
        "ai21",
        "ai21_chat",
        "aiml",
        "aiohttp_openai",
        "amazon_nova",
        "anthropic",
        "anthropic_text",
        "apertis",
        "assemblyai",
        "auto_router",
        "aws_polly",
        "azure",
        "azure_ai",
        "azure_text",
        "baseten",
        "bedrock",
        "bedrock_mantle",
        "black_forest_labs",
        "bytez",
        "cerebras",
        "charity_engine",
        "chatgpt",
        "chutes",
        "clarifai",
        "cloudflare",
        "codestral",
        "cognition",
        "cohere",
        "cohere_chat",
        "cometapi",
        "compactifai",
        "cursor",
        "custom",
        "custom_openai",
        "darkbloom",
        "dashscope",
        "databricks",
        "datarobot",
        "deepgram",
        "deepinfra",
        "deepseek",
        "docker_model_runner",
        "dotprompt",
        "elevenlabs",
        "empower",
        "fal_ai",
        "featherless_ai",
        "fireworks_ai",
        "friendliai",
        "galadriel",
        "gdc",
        "gemini",
        "gigachat",
        "github",
        "github_copilot",
        "gradient_ai",
        "groq",
        "helicone",
        "heroku",
        "hosted_vllm",
        "huggingface",
        "humanloop",
        "hyperbolic",
        "inception",
        "infinity",
        "jina_ai",
        "lambda_ai",
        "langflow",
        "langfuse",
        "langgraph",
        "lemonade",
        "libertai",
        "litellm_agent",
        "litellm_proxy",
        "llamafile",
        "lm_studio",
        "manus",
        "maritalk",
        "meta",
        "meta_llama",
        "milvus",
        "minimax",
        "mistral",
        "modelscope",
        "moonshot",
        "morph",
        "nano-gpt",
        "nebius",
        "neosantara",
        "nlp_cloud",
        "novita",
        "nscale",
        "nvidia_nim",
        "nvidia_riva",
        "oci",
        "ollama",
        "ollama_chat",
        "oobabooga",
        "openai",
        "openai_like",
        "openrouter",
        "ovhcloud",
        "parasail",
        "perplexity",
        "petals",
        "pg_vector",
        "pinstripes",
        "poe",
        "predibase",
        "publicai",
        "ragflow",
        "recraft",
        "reducto",
        "replicate",
        "runwayml",
        "s3_vectors",
        "sagemaker",
        "sagemaker_chat",
        "sagemaker_nova",
        "sambanova",
        "sap",
        "scaleway",
        "scx-ai",
        "snowflake",
        "soniox",
        "stability",
        "synthetic",
        "tencent",
        "tensormesh",
        "text-completion-codestral",
        "text-completion-inception",
        "text-completion-openai",
        "together_ai",
        "topaz",
        "triton",
        "v0",
        "valkey",
        "vercel_ai_gateway",
        "vertex_ai",
        "vertex_ai_beta",
        "vllm",
        "volcengine",
        "voyage",
        "wandb",
        "watsonx",
        "watsonx_text",
        "xai",
        "xiaomi_mimo",
        "xinference",
        "zai",
    )
)
